var fs = require('fs');
const ethers = require('ethers')
const {MongoClient} = require('mongodb')

// const provider = new ethers.providers.WebSocketProvider('wss://rinkeby.infura.io/ws/v3/e875cdf3b3764428ac1347a09e65282d')
const provider = new ethers.providers.JsonRpcProvider('https://cloudflare-eth.com/')
// const provider = new ethers.providers.JsonRpcProvider('https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161')
const mongodb = new MongoClient('mongodb://localhost:27017')

const live= async()=> {
    await mongodb.connect();
    console.log("connected to mongodb")
    // const EthereumIndexerDB= mongodb.db('ethereum-indexer');
    // const BlocksCollection = EthereumIndexerDB.collection('transection')
    const collection = mongodb.db('ethereum-indexer').collection('abi')
    collection.find().toArray(function(err, abi) {
   
        console.log(abi[0].Address);
    
        
        mongodb.close();
      });
    // provider.on("block",async (blockNumber) => {
    // let block = await provider.getBlock(blockNumber)
}
live()  







// import { datatransection } from './blockfetcher.js';
// exports.__esModule = true;
// const  store =require('./blockfetcher')
// const store = new Store();
// const result=store.store

// const state = new appolo.State();
// console.log(state.get('key'));
// const state = require('./blockfetcher');
// const stateManager = require('./state');
// var state = require("./state");
// import { logger } from "@/common/logger";
// const stateManager=require('./state')
// const dataModule = require('./state');
// console.log(stateManager)
// // stateManager.getState();
// stateManager.on('setState',(state)=>{
//     console.log('State fetched:', state);
// });
// setInterval(() => {
//     console.log("state ===================================>", state.getState());
// },2000)


// state.live()
// setInterval(() => {
//     const result = state.getValue();
//     console.log("this is",result); // Output: a new random value generated by the generateValue function every second
//   }, 1000);
// console.log(state.live());
// console.log(state.global);
// console.log(stateManager.getState());
// const Alltransecion = []
// Alltransecion.push(datatransection)
// console.log("this is",Alltransecion);

// const newArrayLength = Alltransecion.push(live)
// console.log("this is",Alltransecion);
// console.log(live);
// console.log("cdscd",stateManager.getState());
// const store = new Store();
// // const data = datatransection
// const value = store.get('someKey');
// console.log("csdcc",value);
// console.log("new---------------------------",data);
// var data = (0, state_1.getData)();
// console.log("csdc", data);
// console.log("dsdfs");
// console.log(live);
// const data = dataModule.getData();
// console.log(data);
// console.log("this is",stateManager.getState());
//  console.log(stateManager.getState()); 
// console.log(stateManager.getState());
// const dataModule = require('./state');
// const data = dataModule.getData();
// console.log(data);
